name: Deployment Workflow
on: [push, workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Getting Code
              uses: actions/checkout@v3
            - name: Install
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Run Tests
              run: npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Getting Code
              uses: actions/checkout@v3
            - name: Install
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Install Dependencies
              run: npm ci
            - name: Build Project
              run: npm run build
            - name: Deploy
              run: echo "Deploying .."
